name: Deploy to another repo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
     - name: Checkout
       uses: actions/checkout@v3

     - name: Setup Node
       uses: actions/setup-node@v2
       with:
         node-version: '16.17.0'
         
     - name: Insall dependencies
       run: npm install
     - name: Compile 
       run: npm run build
    
     - name: Pushes to another repository
       run: |
         git clone --single-branch --branch "main" "https://xrdavies:${{ secrets.PERSONAL_TOKEN }}@github.com/Taoist-Labs/seedao-superapp-app-download-preview.git";
         cd seedao-superapp-app-download-preview;
         git config --global user.name bot;
         git config --global user.email bot@theseedlabs.io;
         cp -R ../build/* .;
         touch .nojekyll
         git add .;
         git status;
         git commit -m "deploy";
         git status;
         git push "https://xrdavies:${{ secrets.PERSONAL_TOKEN }}@github.com/Taoist-Labs/seedao-superapp-app-download-preview.git" --set-upstream main
